name = "project1"
type = "javascript"
account_id = "5179a7cdbdc07ffe04ed220d51330967"
workers_dev = true
route = ""
zone_id = ""
webpack_config = ""

kv-namespaces = [
         { binding = "COUNTER1", id = "cd8073ff139943deb641974a9ecc1c7d" }
]